### ISSUE TITLE
Gentoo

### ISSUE THREAD

**Issue by mazgi** [mazgi/workstation.provisioning#2]
## Todo

- [ ] https://github.com/mazgi/portage-overlay
- [ ] https://wiki.gentoo.org/wiki/Eselect/Repository
- [ ] https://github.com/gentoo/dotnet

**Comment by mazgi** [comment]
> * [ ]  https://github.com/gentoo/dotnet

```shellsession
localhost ~ # cat /etc/portage/package.accept_keywords/dev-dotnet.dotnetcore-sdk-bin.txt 
dev-dotnet/dotnetcore-sdk-bin ~amd64
localhost ~ # cat /etc/portage/package.accept_keywords/dev-dotnet.dotnetcore-sdk-bin-common.txt 
dev-dotnet/dotnetcore-sdk-bin-common ~amd64
localhost ~ # emerge -uavq dev-dotnet/dotnetcore-sdk-bin
```
